baseURL = 'http://sajadjalilian.github.io/'
languageCode = 'en-us'
title = 'Sajad Jalilian'
theme = 'hugo-paper'

[params]
  twitter = 'Sajad_Jalilian'
  github = 'SajadJalilian'
  linkedin = 'sajadjalilian'
  rss = true