baseURL = 'http://sajadjalilian.github.io/'
languageCode = 'en-us'
title = 'SJ blog'
author = 'Sajad Jalilian'
theme = 'hugo-paper'
paginate = 5
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[taxonomies]
  tag = "tags"
  category = "categories"
  

[params]
  twitter = 'Sajad_Jalilian'
  github = 'SajadJalilian'
  linkedin = 'sajadjalilian'
  rss = true

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/en-blog/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 12
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 13
  [[menu.main]]
    identifier = "fa-blog"
    name = "فارسی"
    url = "/fa-blog/"
    weight = 20


# giscus
[params.giscus]
  repo = 'SajadJalilian/SajadJalilian.github.io'                 # see https://giscus.app for more details
  repoId = 'MDEwOlJlcG9zaXRvcnkxNjQzNDY3NDE'
  category = 'Announcements'
  categoryId = 'DIC_kwDOCcu7dc4Cb_N2'
  mapping = 'pathname'
  theme = 'light'
  lang = 'en'

[services]
  [services.googleAnalytics]
    ID = 'G-J5QDV547XJ'